### ISSUE TITLE
フレームワークの選定

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#1]
- 「バックエンドからもらったデータをもとに構造に反映したい」だけなら素のVueで苦労なくできそう
- SPAにして状態が云々とか、SSAとかのファンシーな機能を要求するならちゃんとしたフレームワークがいる

**Comment by equal-l2** [comment]
がっつりサーバと密結合で状態を持って動く感じではないので、Nuxtほどしっかりしたのじゃなくていいんではないかな……と個人的には思っています

**Comment by equal-l2** [comment]
動的レンダリングが必要なページだけ<script>でVueかなんか読み込んで動かす感じで出来そうな気がする

**Comment by h-takeyeah** [comment]
> がっつりサーバと密結合で状態を持って動く感じではないので、Nuxtほどしっかりしたのじゃなくていいんではないかな……と個人的には思っています

確かにですね．CI周りはNuxt等しっかりしたフレームワークがあった方が例があるので開発速度を上げるのに役立つという話をstkさんから聞いたのですが，数人でやるなら素のJSでも問題ないかなあという気がするので青シャツさんの意見に賛成です．

**Comment by equal-l2** [comment]
なるほど、テストやデプロイまわりをしっかりやるならオールインワンのフレームワークの方に軍配が上がるのは確かですね。

**Comment by h-takeyeah** [comment]
今，モックアップがsu-its/ams-frontendに上がっているので，それに毛を生やし草を生やしていくということにします．HTMLをいくつも配置したことによってHistoryがやかましくなるのはさしたる問題ではないと思いますし，素のJSでできることは素のJSでやらせた方が良いと思いますから．

**Comment by h-takeyeah** [comment]
issueはここでクローズしますが，もしフレームワークの類を使いたい需要が出てきたらまたオープンしましょう．
