### ISSUE TITLE
入退室記録をcsvで書き出させる機能

### ISSUE THREAD

**Issue by ghost** [su-its/ams-frontend#10]
期限をどうするか、が全く決まっていない。

vuetifyなどを使えば、必要なデータを選択することが出来るだろうが、

現在ヒアリングした情報によると、2か月分(ボタン押下時から2か月前まで)のCSVファイルをダウンロードすれば良いと思われる。

**Comment by equal-l2** [comment]
`/access_logs`から全件持ってこれるので、フロントエンドでCSV構築してもいいかもしれないですね

**Comment by h-takeyeah** [comment]
> フロントエンドでCSV構築して

自分も方針はそれでいいと思います．実装方法が全く分からないので使えそうなライブラリが無いか探してみます．

緊急の課題ではないし，CSVだけの問題でもないですが，一つ懸念があります．それは特定の一人のログだけCSVに出したいというユースケースがあった場合に少なくともバックエンド側では現状対応できないということです．特定期間なら何とかなるかもしれないですが，学籍番号で絞ることはできないですから厳しそうです．その辺いかがでしょうか．

現状の構成でいくなら

1. `/access_logs`から全件持ってくる
2. Array.prototype.filter()か何かで特定の学籍番号のレコードだけにして
3. 書き出し担当のcomponentに渡す

になりますかね．辛い．

**Comment by ghost** [comment]
@equal-l2 え、それマジで言ってる？

普通にAPIのwhere句内をqueryパラメータ(APIのURLのお尻につけるって意味)で変えれるようにするのが一番楽で、誰も困らんロ思うのですが

**Comment by ghost** [comment]
@equal-l2 @h-takeyeah 学籍番号で絞るのすっかり忘れてましたが、それはさておき、今使ってるAPIってSQL的な絞り方出来ないんですか？

逆にこの機能はむしろ簡単だと思ったんですが、素人は黙っとれなら、そうですね、って感じですけど

**Comment by equal-l2** [comment]
where句を考えなしに露出するとインジェクションが怖くないですか？

---

入室時刻の範囲を受け取るパラメータは元々あったんですが、使っていなかったので一旦消しました。

**Comment by equal-l2** [comment]
単にプリペアドにしとけばいいだけか……

**Comment by ghost** [comment]
@equal-l2 誰も考えなしにやれとは言ってないし、ヴァリデーションはやるんじゃないんですか？

どんなSQLの使い方するのかドキュメントが存在しないので、リバースエンジニアリングで把握するしかないですけど、

そんな全件検索しかできないシステムってそんなのあります？というお気持ち

**Comment by equal-l2** [comment]
少なくとも自分は「特定の一人のログだけCSVに出したい」みたいな~ふざけた~まだ存在しないユースケースは実装しなくていいと思います
それを見たいならユーザが落としてきたCSVをExcelで開いてソートすればいいのですから。

**Comment by equal-l2** [comment]
あー、もしかして「(2ヶ月分とかそういう枠に縛られず)任意の条件を適用したaccess_logsをCSVとして落としてきたい」という話ですかね

**Comment by ghost** [comment]
> あー、もしかして「(2ヶ月分とかそういう枠に縛られず)任意の条件を適用したaccess_logsをCSVとして落としてきたい」という話ですかね

そうです、だからwhere句につけるデータをqueryにしたいといった訳です

**Comment by equal-l2** [comment]
そうなるとwhere句を直で渡すしかないかなあ……
何にしても「渡されたwhere句に合わせてデータを吐くエンドポイント」を別で作るのがいいですね

**Comment by ghost** [comment]
> 少なくとも自分は「特定の一人のログだけCSVに出したい」みたいな~ふざけた~まだ存在しないユースケースは実装しなくていいと思います
> それを見たいならユーザが落としてきたCSVをExcelで開いてソートすればいいのですから。

そんなことがあるかどうかは知りませんが、滅茶苦茶データが多い(出入りが激しい研究室だったら等)場合、

時間を区切ってかつこの人だけの情報を取りたい、というユースケースは正直運用してみないと分からないので、

実装だけして使わないならそのままフロントエンドから機能ごと削除すれば良いだけの話だと思います。

**Comment by ghost** [comment]
> そうなるとwhere句を直で渡すしかないかなあ……
> 何にしても「渡されたwhere句に合わせてデータを吐くエンドポイント」を別で作るのがいいですね

フロントエンドとしては、同一のベースURLからデータを引っ張ってこれる事を希望したいです。

パラメータとしては、queryに変換すれば大丈夫な感じにすればそれっぽくなると思います

**Comment by h-takeyeah** [comment]
自分も口を別で作らなくてもクエリパラメータに渡してくれればそれに沿った結果を投げるエンドポイントは書けるので同一のベースURLから～に賛成です

**Comment by equal-l2** [comment]
確認したいんですが、今のワークフローとしては「バックエンドがCSV構築してそれを投げてくる」のと「バックエンドはaccess_logs同様のArrayで投げてきて、フロントでCSVに組み立てる」のどちらを想定してますか？

前者だったらページネーションしないと思うので別エンドポイントの方がいいと思います。

**Comment by equal-l2** [comment]
別エンドポイントというか `/access_logs/csv` みたいに掘る感じ

**Comment by ghost** [comment]
>確認したいんですが、今のワークフローとしては「バックエンドがCSV構築してそれを投げてくる」のと「バックエンドはaccess_logs同様のArrayで投げてきて、フロントでCSVに組み立てる」のどちらを想定してますか？

自分も前者ならそれっぽいことはやったのですが、今回のアーキテクチャだとjson2csvみたいなモジュールを持ってくるか、

何とか自分でビルドするかどっちかの方が早そうですね....

まあ仕事で使ったのlaravelだったので...ね...

**Comment by h-takeyeah** [comment]
> ページネーションしない

確かにそうですね．しかしそうすると(機能としての需要は低いとはいえ)今度は表の方が番号で絞れる恩恵を使えなくなって不便じゃありませんか？

**Comment by equal-l2** [comment]
フロントエンドUIにおける入退室管理記録表表示においては「入室時刻降順で表示」のユースケースに絞っていいと思っています。
そこを逸脱したいならCSVが柔軟に吐き出せるわけですからそちらを使ってもらえればいいかなと。

**Comment by h-takeyeah** [comment]
@Stroheim001 
> どんなSQLの使い方するのかドキュメントが存在しない

ここで話題になっている部分について述べます．以下の`listAccessLogs`という関数が`/access_logs`へのリクエストが来た時に呼ばれる関数になります．

```typescript
async function listAccessLogs (
  since?: string, until?: string,
  order = 'DESC', limit = 100, offset = 0
) {
  try {
    const [rows, _] = await mysql.query(
      `SELECT * FROM ${TABLENAME} ` +
      "WHERE exited_at >= IFNULL(?, '1970-01-01') " +
      'AND entered_at < IFNULL(?, ADDDATE(CURDATE(), 1)) ' +
      `ORDER BY entered_at ${['ASC', 'DESC'].includes(order) ? order : 'DESC'} ` +
      'LIMIT ? OFFSET ?',
      [since, until, limit, offset])
    return [rows, null]
  } catch (err) {
    return [null, err]
  }
}
```

JSDocとしてあえて書くと
```javascript
/**
 * 入退室記録を取り出す関数．現状では`since`と`until`(と`order`)には問答無用で`undefined`を
 * 入れているので，実質全件取得用の関数になっている
 * @param {string} since - 検索範囲の開始日の文字列表現
 * @param {string} until - 検索範囲の最終日の文字列表現
 * @param {string} order - 並び順
 * @param {number} limit - LIMIT
 * @param {number} offset - OFFSET
 * @returns {Promise<any[]>}
 */
```

**Comment by ghost** [comment]
@h-takeyeah あ、了解です。
やっぱり、どんなORM使っても似たような感じになるんですね。
承知しました。まあ、強いて言うと、どんな使い方っていうよりも、もし自分が改良とかいれたいときどこ弄ればいいんだろ的な疑問でしたｗ

**Comment by equal-l2** [comment]
@Stroheim001 
https://github.com/su-its/ams-backend/pull/76 にてバックエンド側の対応ができましたので、フロントエンドの実装よろしくお願いします。

**Comment by ghost** [comment]
@equal-l2 了解です。

**Comment by ghost** [comment]
@equal-l2 @h-takeyeah 
やっとこさ作り始めたのですが、「UTF-8」で出力するべきなのか「sjijs」で出力するべきなのか、が我々には
分かりようがありません。んで、どうやらExcelのverによって違いがあるらしいのですが、

流石にこれ以上ボタン数を増やすとUXが下がりすぎる気がするのですが、かといってユーザが求めているものが
ちゃんと定まってないのでそこはちゃんとしてないとやばい気もします。
幸い今回出力するのは数字なので、どっちでも良いような気もしますが、さてどうしましょう...というお話です

[qiitaの記事](https://qiita.com/kum44/items/d11f97ecee3e46d3195d)

**Comment by equal-l2** [comment]
UTF-8もShift-JISもASCIIのスーパーセットなので、ASCIIの範疇で出力されていれば文字化けは起こらないはずです。
将来的にnon-ASCIIな出力をするとなると話が違ってきますが……

**Comment by equal-l2** [comment]
UTF-8で出力するにもBOM付きとBOMなしがあって、Office系列はBOMを欲しがるっぽいですね（Office死すべし）

**Comment by ghost** [comment]
@equal-l2 あ～、そうなんです。一応数字とかだけなので、文字化け起こらんくね～とは思うんですが、将来の拡張性とか

ないとは思いますが、文字化け起きたらとか、BOMの話とかそれ考えるとOffice製品で見る、という前提を作った場合、それ用のUIとか使い勝手を考えないと 👎 って言われる

**Comment by ghost** [comment]
というか、2016以前と以後でBOMがいるかいらんか違うみたいでテスティングが無理ｗｗｗｗｗｗｗｗｗｗｗｗ

**Comment by equal-l2** [comment]
とりあえず「最新版のExcelで読み込む」ことを考えることにすると、以下の2パターンに絞れますね。
- ASCIIの範疇の出力しかしない場合、なんでもよい(「UTF-8」が無難)
- ASCII外の出力が将来的に予想される場合、「UTF-8(with BOM)」
