### ISSUE TITLE
現在在室している人、入室時間を表示する機能

### ISSUE THREAD

**Issue by ghost** [su-its/ams-frontend#11]
在室している人の総数も数えればいいだけの話だし、APIに任せるという手もあるので、ちゃんと要件を詰めておきたいです。

**Comment by equal-l2** [comment]
@h-takeyeah 現状入室時間は表示してないですが、表示する予定はありますか？

**Comment by h-takeyeah** [comment]
@equal-l2 考えていませんでした．仮にindex.vueの画面がずっと表示されているとして，そこに入室時間が表示されているのは，完全に主観ですが，見えすぎだと感じるので，今のまま番号と(あれば)名前を表示しておくのが良いと思います．

**Comment by equal-l2** [comment]
ではこのissueに関する実装はひとまず終わったということで、閉じます。

**Comment by ghost** [comment]
@equal-l2 @h-takeyeah いったんクローズした話蒸し返して申し訳ないのですが、

一旦このモックアップを見せてそもそもこの納品で納得頂けるかヒアリングして欲しいです。

実際のSIerの開発においてヒアリングはとても重要な要素です。当然と言えば当然なのですが、エンドユーザが使えない、と判断されては元も子もないからです。なにとぞ確認のほどよろしくお願いします。

**Comment by h-takeyeah** [comment]
@Stroheim001 ヒアリングの件ですが，とりあえず某室の担当の先生にこのモックアップを見せてみようと思います．それから室員からも何人かに聞けたら聞いてみます

**Comment by ghost** [comment]
@h-takeyeah 
ヒアリングすると、無限に要求が出てくると思うので、優先順位(プライオリティ)という概念を強く意識してください。

この人が本当に求めているものは何か、例えばCSVで保存してるけど、本当はExcelフォーマットのほうが嬉しかった。

@h-takeyeah 
そこにマクロも組んであったらすごく嬉しかった、とかそういったじゃっかん想像力を働かせる部分が大きくなるとは思いますが、頑張ってください。

もし、ヒアリングが難しそうなら私が間に入ることも可能ですし、webカメラもあるので呼んでください。

緊急で必要になった時用に電話番号を教えておきます。たぶんいらないと思いますが万が一です。slackのDMに貼っておきます

**Comment by h-takeyeah** [comment]
日が決まったらお伝えしますね

**Comment by ghost** [comment]
@h-takeyeah 今日じゃないんか～い！！www

**Comment by h-takeyeah** [comment]
@Stroheim001 ProjectsのWIPに今更ですが移動しておきました．

ヒアリングのタイミングは決まってませんが，ヒアリングでは特に以前@equal-l2 さんから質問のあった入退室時間を「現在、〇人が在室中です」のページ(indexページ)に表示した方がいいか，それともない方がいいかについて確認を取りたいと思います．

それ以外の部分は実装面ではほぼ出来上がったと思うのでヒアリングができたらこのissueはクローズしようと思います．

**Comment by ghost** [comment]
@h-takeyeah 申し訳ないのですがヒアリングで聞く切り口が違い過ぎて、ちょっと説明するとアホみたいに長いのでhackMDでなんか書いておきます。

**Comment by h-takeyeah** [comment]
@Stroheim001 ありがとうございます！

**Comment by equal-l2** [comment]
ヒアリングで特に問題が出なかったようなので、改めてクローズします。
