### ISSUE TITLE
eslint をnuxtできちんと動かす．JavaScript Standard Style も適用する

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-frontend#16]
このissueを閉じるときに達成されていること
- eslintがちゃんと走る
- JavaScript Standard Style(標準とは言ってない)がeslintのフォーマットルールになっている

**Comment by equal-l2** [comment]
`@nuxtjs/eslint-config-typescript` は `standard` をベースにしています。

https://github.com/nuxt/eslint-config/blob/6ac852033430d4c0a9dae17cbfeb9531218d55f3/packages/eslint-config/index.js#L8

**Comment by ghost** [comment]
@equal-l2 @h-takeyeah 
こちらの作業と並行して、私はnuxt化に専念してもよろしいですか？

(そろそろ今日は寝ますが...)

**Comment by equal-l2** [comment]
eslint周りは自分たちがやるので、mockのページ(っぽい感じのもの)が動くのを目標にそちらに専念していただければと。

**Comment by h-takeyeah** [comment]
@equal-l2 よろしくお願いします．サーバー側のwebsocketの口は鋭意実装中です
