### ISSUE TITLE
モックアップのNuxt化

### ISSUE THREAD

**Issue by ghost** [su-its/ams-frontend#19]
現在 @arkwnet さんが作って頂いたソースを元にnuxt風にしていきたいと思います。

ただ、nuxtの仕様上、動的にページが変更できるのはcomponentsだけなので、どのような構造なのかは後で、図で解説したいと思います。

**Comment by equal-l2** [comment]
今後の機能追加・バグ修正はそれぞれissueに分けてやってください。
