### ISSUE TITLE
フロントエンドの要件決定

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#2]

**Comment by ghost** [comment]
@h-takeyeah 

- 現在，在室している人数を表示する機能
- 現在，在室している人の学籍番号のリストを表示する機能

これは機能上は確かに違うかもしれないけど、同じページに横に在室人数を置いてるだけで充分だと思うので、

特に問題にならないと思われる。高速化を図りたい場合、API側で人数を表示しておけばフロントエンド側はかなり楽が出来ると愚考します。

ex:
```
{
  "people": 2
  "data": [
      {何かしらのデータ}
  ]
}
```

**Comment by equal-l2** [comment]
各要件がissueに切り分けられたので一旦閉じます。
