### ISSUE TITLE
ページネーション

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#23]
動いてない気がするので直す

**Comment by equal-l2** [comment]
https://github.com/su-its/ams-backend-nodejs/issues/57#issuecomment-797860790
>meta情報って直ってるんですよね？

「`prevPage`と`nextPage`を不在時nullにしたか」という意味であれば完了してます。
よろしくお願いします。

**Comment by ghost** [comment]
@equal-l2 
了解です。たぶん、vuetifyとほぼ同じ要領だと思うのでトライしてみますね
