### ISSUE TITLE
インデントをスペースかタブのどちらかに統一したい

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-frontend#3]
@arkwnet @equal-l2 今の`mockup`ブランチのソースコードはインデントにタブを使用していると思います．自分はインデントといえばスペース2つ派なのですが，どちらを使うことにしましょう？

**Comment by equal-l2** [comment]
自分はHTMLに関しては2スペース派です。

プロジェクトで合わせたいなら .editorconfig を作成すると透過的に扱えるので楽です。
#5 で一旦2スペースで設定しましたが、タブがいいようならそちらに合わせます。

CC: @arkwnet

**Comment by ghost** [comment]
@arkwnet @equal-l2 @h-takeyeah 
素敵なhtmlファイルをありがとうございます、って思うんですけど、htmlじゃなくて

pugではダメですかね(保守性を考慮してます)

[pugに関するqiita](https://qiita.com/yun_bow/items/d21586b51f87d781a857)

**Comment by equal-l2** [comment]
HTMLの代わりにpugを使った方がいい、という意味でしたら賛成しかねます。
現在のメンバーは全員ひとまずHTMLが書けますし、今後メンバーが増えるとしてもHTMLがわからないようならpugのコンセプトも同様に理解できないはずです。

**Comment by ghost** [comment]
@equal-l2 
ケチをつけるようでアレだけど、ヴェロシティの観点から `現在のメンバーは全員ひとまずHTMLが書けます` が優先されるために、新しい学習コストがかかるpugがダメだというのは納得がいく回答ではありますが、

`HTMLがわからないようならpugのコンセプトも同様に理解できない` っていうのは、htmlを分からない人間はmdをかけないと同じくらいの暴論(少なくと自分はそう思う)なので、普通に前者の学習コストが惜しいので無理です、とだけ言えば良いと思います。

後、何故私が早めにpugの導入を推し進めているのかについては、スイッチングコストが高すぎるのでやるなら今しかないと思っているからです。さらに言うと、フロントエンドはAPIに比べてテストが難しすぎるから、です。

却下するのはそちらにお任せしますが、後輩が引き継いだ時に困らないようになっておいて欲しいです。

**Comment by equal-l2** [comment]
> フロントエンドはAPIに比べてテストが難しすぎるから

この文脈でテストの話が出てきたということは、pugでは何かテストに便利な機能があるのでしょうか。
それがあるのなら参入コストを上回って導入する理由になるかもしれないので詳しく教えていただきたいです。

---

> htmlを分からない人間はmdをかけないと同じくらいの暴論

これは性質が違うと思います。

以前「HTMLの階層構造わからないでMarkdown書いてるの困るよね」というような話をしたと思います。
この話は裏を返せば「HTMLが全くわからなくてもMarkdownは書ける」ということです。

一方で、PugはHTMLを全く知らない人間には門戸を開いていません。
これはPug公式ホームページで最初に出てくるコードです。
```pug
//- template.pug
p #{name}'s Pug source code!
```
HTMLを知らない人間にはこの `p` の意味がわからないはずです。
そしてその意味を知るにはまずHTMLの知識を学ぶ必要があるはずです。
(Markdown的に「とりあえず `p` って書けばこうなるから……」という運用もできなくはないですが)

**Comment by ghost** [comment]
@equal-l2 申し訳ないです。確かに、pugがテスティングに寄与することはないと思います。(強いて言うなら、IDとかclass名を間違いにくい？くらいだと思います。)

確かにmdとpugを同質に扱うのは良くないとは思います。

まあ、正直それほど大規模なコードにならないと思うのでhtmlで書いててもやばい事にはならないとは思いますが10000行超えるような、マイグレーションしたくてもどうしようもない、ような事態には今回はならなさそうなので、良いかもしれないですね。

まあ、正直自分がpugだと楽できるくらいのしょうもないことしか考えてなかったと言われれば否定できないのでｗ

**Comment by equal-l2** [comment]
> 自分がpubだと楽できる

これは自分もHTMLだと(学習コストがないので)楽できるという点では同じですね。

---

テンプレートエンジンが役立つのは似たようなコード(ボイラープレート)がいろんな場所に散らばっている場合だと思うので、大規模開発ではPugは確かに便利そうです。
ただ、 @Stroheim001 さんもおっしゃった通り今回はどうなってもそこまでの大規模感にはならなそうなので、HTML以上のものを使うインセンティブが見出せませんでした。

一応、この機会にPugを覚えるという考えもありかもしれないので、最終判断は @h-takeyeah くんに一任したいです。

**Comment by ghost** [comment]
@equal-l2 そうですね、積極的に使う材料はないですね。

まあですので最初に却下してもらって良いですよ、と言ってたんですけど、あんまりニュアンスが伝わってなかったですね。すみません

最終判断はお任せしますので、それに従いますが、命名規則はちゃんとしてくださいね。

**Comment by equal-l2** [comment]
いつの間にか解決しました
