### ISSUE TITLE
バージョンの表示画面の必要性

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#30]
いるなら裏のAPIを作らないといけないし、いらないなら消さないといけないし、納入前に決めなければならない。

**Comment by h-takeyeah** [comment]
個人的にはフロントエンドにバックエンドのバージョンを表示する需要はないです．

**Comment by equal-l2** [comment]
フロントエンドのバージョン表示はどうしますか？
`package.json`から読んでもいいし、ハードコード(この場合リリース時のdocが必要)してもいいですが。

**Comment by h-takeyeah** [comment]
フロントエンドのバージョン表示について．できるなら`package.json`から読むのが良いです
