### ISSUE TITLE
入室・退室時刻のフォーマット

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#33]
現状タイムスタンプは`2021-03-14T14:48:56.000Z`のようにISO8601形式で表示されている。
ただこの表記だと少し読みにくいので、`2021-03-14 14:48:56`のような形式にしたい。
多分moment.jsでフォーマットしてやればいいだけだと思う。

~(そもそもJSTのくせにUTCを名乗っている問題もあるがそれはバックエンドの問題だし現状困ってないので放っておく)~
普通にローカルタイムをUTCに変換したものを送ってるだけなので問題なかった。

**Comment by equal-l2** [comment]
~いや、moment.jsでフォーマットしようとすると(フロントエンドが`ja`ロケールなので)UTCから日本時間に時差変換されてしまう。
バックエンドの方を直さなければ……~
直す必要がなかった

**Comment by ghost** [comment]
@equal-l2 
momentのlocaleからjaを外せば済む話だし、どうしてもjaが欲しいならそこから.add(-9, 'hour') すれば目的は達成できる

DB側で不整合起こしてる問題だとは思うが、どう判断するかはたかはしさんに委ねるが、DB側の問題を放置した場合、

ITSからの要求として、正しく表示されるように仕様変更を要求される可能性はゼロではない
(amsはそもそもITSのシステムなのでITSが仕様変更を要求する可能性、および権利を棄却できない)

**Comment by equal-l2** [comment]
DBはローカルタイムゾーンで時刻を入れてるので、バックエンドでちゃんとそこの意図を汲み取ってやるのが正しい解決方法だと思います。
MariaDBに接続するときのコンフィグでなんとかできるっぽいので試行中です。

**Comment by ghost** [comment]
@equal-l2 では現状問題のあるデータで運用してるのはITSだけでありそれはITS個別の問題なので、mariaDBでなんとかなるよ～フロントはそのままでええよ～って話なんですね？

**Comment by equal-l2** [comment]
MariaDBの`DATETIME`型はタイムゾーンが付いてなくて嫌でもDBのローカルタイムで格納されるはずなので、そこをちゃんと認識してハンドルするのはバックエンドの仕事ですね。
なのでフロントでやるべきことはそれをちゃんとフォーマットするだけということになります。

**Comment by ghost** [comment]
別にmoment.js使えばフォーマットは何とかなるけど、この場合は `locale:ja` というconfigが邪魔になるかどうなのかちょっと試験してみないといけないね

**Comment by equal-l2** [comment]
ロケールはこのままでいいと思ってます。
現状の問題のそもそもの原因はバックエンドが偽りのタイムゾーンを吐いてることなので。

**Comment by ghost** [comment]
@equal-l2 
では私は、ユーザフレンドリな出力にのみ注力する、という認識で良いですか？
(不安材料としては)ちなみに、CSVで落とすときもmoment使って形変えろ的な事も検討しないといけないですか？

**Comment by equal-l2** [comment]
いろいろ調べた結果、時刻は以下のような過程を踏んで変形されてるので特に現状で問題ないことがわかりました。
1. DBには`DATETIME`(ローカルタイム)で格納されている
2. これがバックエンドではちゃんとローカルタイムとして解釈される（ただしUTC換算で表示されるので私が勘違いしていた)
3. JSTとして解釈された時刻がUTCに変換されてフロントエンドに送られる

なので、フロントエンドでやるべきことはmoment.jsに読ませてフォーマットすることです。
PR送ります。

**Comment by ghost** [comment]
@equal-l2 お、おうありがとうございます。

え？でも、UTC状態でJSONになってCSVでも来るんでしょ？

控えめにいってやばい感あるけど、お願いとして、OpenAPIに特筆大書すべきこととしてUTC表記だけどこれ嘘って話は書かないとやばくね？
ていうかバックエンドでなんとかならないの？CSV落とすとき結局何やらせんといかんくてやばいんでしょ？

**Comment by equal-l2** [comment]
いえ、ちゃんと時差は変換されてるので嘘ではないことがわかりました。
フロントエンドで日本時間に戻したければ(タイムゾーンがちゃんと設定されているので)momentに放り込めばいいだけのはずです。

**Comment by equal-l2** [comment]
あー、Vuexに突っ込む段階でmomentのオブジェクトにマップした方がいいのかな……

**Comment by ghost** [comment]
@equal-l2 CSVファイル化する前に一度全部momentでja化しろって話なのと、
actionsも変更いるって話でしょ？全時間データに対して....

**Comment by ghost** [comment]
@equal-l2 過失はそっちにあるのかもしれないけど、そんなことはエンドユーザにとってはどうでも良い話だから、
俺がケツふけって話なんでしょmomentで変換かけて

**Comment by ghost** [comment]
vuexについては、そんなに難しい話ではないから( `locale:ja` かけるだけでええなら)

セッタで変換かまして何とかすれば良いから構わんけど、CSVをforeachかけて全部やんのか、バグ起きてないか確認するのしんどいな

**Comment by equal-l2** [comment]
要はここ
https://github.com/su-its/ams-frontend/blob/73a56063e7f0bef043d7375132433ee8b4e1dc09/store/logging.js#L88-L92
で`Response.data.data`を全部momentjsのオブジェクトにmapしてから`'SET_ACCESS_LOGS'`に投げておけばよさそうですね。

で、文字列として出すときは`format()`すればちゃんと`2021-03-24T14:54:32+09:00`みたいにJSTかつISO8601の形式で出てくれるので、これで何とかなりませんか？

**Comment by ghost** [comment]
@equal-l2 いや、別にどこにループ作って、時間の表記を対応させるのかはかまんけど...

(自分はSET_ACCESS_LOGSのpayLoadでlodash使ってloop回して誤魔化そうかなと思ってて、そっちの方がAPI治った時に、修正箇所が小さくて済むかなと思ってた)

今更APIをどうこうするのは無理なのね

**Comment by equal-l2** [comment]
タイムゾーンに関しては結局今のAPIで正しい動作をしてることが分かったので、バックエンドからDate形式で入室・退室時刻を送ってる限りは必要な作業のはずです。

**Comment by ghost** [comment]
@equal-l2 大変申し訳ありません。話の意図が見えてこないのですが、結局APIはバグってないので、私に責任がある、と言う話で、それは表示部、およびCSVダウンロード部の話をしているのでしょうか？
表示を変えるのは一瞬で終わりますし、CSVも多少なり細工すれば何とかなるとは思いますが、結局話の意図は何でしょうか？

**Comment by equal-l2** [comment]
すみません、話を原点に戻すと、やりたいことは表示部分のフォーマットを`2021-03-14 14:48:56`(`YYYY-MM-DD HH:mm:ss`)みたいにして少し見やすくしたい、ということです。
その内部実装として、momentjsの`format()`を使いたいという話でした。

**Comment by equal-l2** [comment]
CSVに関しては、バックエンドから来る時刻はタイムゾーンがUTCと明示されているのでそのまま書き出してもいいかもしれません。

**Comment by ghost** [comment]
> 話を原点に戻すと、やりたいことは表示部分のフォーマットを2021-03-14 14:48:56(YYYY-MM-DD HH:mm:ss)みたいにして少し見やすくしたい、ということです。

うん、ここだけ書いて欲しかったです。それに関しては了解しました

**Comment by equal-l2** [comment]
stkさんには説明書の方に注力してもらう方が良さそうなので、
- 表示の修正
- ストアへの格納時点で時刻を`momentjs`オブジェクトにマップする

の部分は自分が書いてもいいですか？

**Comment by ghost** [comment]
@equal-l2 いやいいよ、storeでmomentかけられちゃうと、vuexが持ってるデータで十分なのに、さらにformat変えるから、

見た目変わらんけど、同じこと二回する事になるよ？？

表示の変更程度なら自分が2行書けば終わる

**Comment by equal-l2** [comment]
あっ、CSVやる時もVuex経由でやる気でいました。すみません。
それではすみませんがそちらで変更よろしくお願いします。

**Comment by ghost** [comment]
CSVはvuex関係ないよ～

詳しく知りたかったらlogicを追って欲しいんだけど、そもそも参照してるページが必ずしもダウンロードしたいデータとは限らないやん？

**Comment by equal-l2** [comment]
さっき言われた瞬間に全てを思い出しました……

**Comment by ghost** [comment]
悲しみ...
