### ISSUE TITLE
Nuxt3へのマイグレーション

### ISSUE THREAD

**Issue by negitoro001** [su-its/ams-frontend#61]
@equal-l2 @h-takeyeah 
佐竹です。nuxt2が、今年末でEOLになるので、nuxt3へマイグレーションしたいのですが、如何でしょうか？

開発は私が主体でやろうと思うので、(マイグレーション作業はやったことがあります)

開発用のslackかdiscordへの招待リンクをおくっていただけると幸いです。

メンションが間違っていたらすみません。

**Comment by h-takeyeah** [comment]
@negitoro001 佐竹さんお久しぶりです。たかはしです。

COVID-19 対策が一時期ほどは叫ばれなくなってきたことからこのシステムはもう今 ITS では使っていません。また他の研究室等に納めた分に関しても約款上ですでにサポートを打ち切っています。

自分も ITS からは離れているのであまり積極的にやっていく意思はありません(それはそれとしてマイグレーション作業には興味はありますが)。

ですのでお気持ちは嬉しいのですが、マイグレーションしても今後それっきりとなる可能性はあります。それでもよいならこのリポジトリをフォークしてもらって作業してもらうのが安牌かなと思います。

よろしくお願いします。

**Comment by negitoro001** [comment]
@h-takeyeah nuxt3のマイグレーションは一度やったので、興味がある人がいたら、何人か集めて、discordあたりに集まって、作業できたら～、と思ってます。

なかなかメンテされてなさそうだったのですが、やはり使われてなかったのですね。了解です。

それとnuxt3はtypescriptに最適化されてるので、型安全に開発ができるので、色々とv2でできなかったことが出来るのではないか？と思います。

**Comment by h-takeyeah** [comment]
興味があるとは書きましたがいま諸々リアルが忙しくメンテする余裕がありません。なので参加者を集めるのも自分がそれに参加するのも協力できません。ごめんなさい。

**Comment by negitoro001** [comment]
@h-takeyeah 
興味がある人がいないか、声をかけるだけで大丈夫です。slackで声かけてもらえたらなって思います。

今、自分ITSのslackにいないので...(なんであんなことしたんだろうと後悔)

**Comment by negitoro001** [comment]
@h-takeyeah 年末年始にすいません。
一応nuxt3用にマイグレーションしたんですが、誰にレビュー依頼したらいいかわからないのですが、
誰にメンションすればいいでしょうか？
(そもそも使ってないから意味ないって言われればそうだと思いますが...)

**Comment by h-takeyeah** [comment]
@negitoro001 お疲れ様です、マイグレーションありがとうございます。レビュアーとしては私をつけてください。よろしくお願いします🙇

**Comment by negitoro001** [comment]
@h-takeyeah あ！！自分フォークして作ってるので、レビュアーつけれないので、
レビューお願いしたいです。ちなみに、backendの方も修正加えてます。
#62

https://github.com/su-its/ams-backend/pull/115

**Comment by h-takeyeah** [comment]
Oh…！理解
