### ISSUE TITLE
入退室記録を表示する機能

### ISSUE THREAD

**Issue by ghost** [su-its/ams-frontend#8]
最低限必要な要件であり、学籍番号、入室時間、退室時間を表示する

入室時間の降順で表示されると思われる。

ページネーションがあるため、まずアクセスした際に表示すればエンドユーザが満足すると思われる。

**Comment by equal-l2** [comment]
ヒアリングで特に指摘がなかったようなのでクローズします。
実際に提供されてからの問題については個々の問題についてissueを立ててください。
