### ISSUE TITLE
フレームワークについて(再)

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-frontend#9]
#5で一旦Vueを採用しました。

**Comment by ghost** [comment]
@h-takeyeah 

[nuxtとvueの違い](https://itnews.org/news_contents/nuxt-js-over-vue-js-when-should-you-use-it-and-why#:~:text=Nuxt.js%E3%81%A8Vue.js,%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84%E3%81%A8%E3%81%84%E3%81%86%E7%82%B9%E3%81%A7%E3%81%99%E3%80%82&text=Vue%E3%81%AE%E5%A0%B4%E5%90%88%E3%81%AF%E3%80%81%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88,%E7%99%BA%E7%94%9F%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AF%E3%81%82%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82)

なんか重たい云々が描かれてないのと、そもそも、initializeするとそれっぽいディレクトリが出来る事、pagesフォルダがそのままURLとして機能することから、学習コストや難易度の観点からnuxt.jsを提案します。

**Comment by equal-l2** [comment]
close with 32a303f
